functional = "pbesol"
version = "1.3.0"
program = "many"
extension = "upf"
extra = ["precision"]
sssp_handle = "pbesol_precision_1-3-0"
extracted_on = "2026-04-16T14:43:43.860"
type = ["nc", "us", "paw"]
relativistic = "sr"
collection = "sssp"
