functional = "pbesol"
collection = "dojo"
program = "jth"
extension = "xml"
extra = ["standard"]
pseudodojo_handle = "paw-sr-11_pbesol_standard_xml"
extracted_on = "2024-12-27T20:34:20.486"
version = "1.1"
type = "paw"
relativistic = "sr"
