functional = "pbesol"
collection = "dojo"
program = "oncvpsp3"
extension = "upf"
extra = ["stringent"]
pseudodojo_handle = "nc-sr-04_pbesol_stringent_upf"
extracted_on = "2024-12-27T19:53:58.988"
version = "0.4.1"
type = "nc"
relativistic = "sr"
