functional = "pbesol"
collection = "sssp"
program = "mixed"
extension = "upf"
extra = ["efficiency"]
sssp_handle = "pbesol_efficiency_1-3-0"
extracted_on = "2026-04-20T14:17:37.580"
version = "1.3.0"
type = "mixed"
relativistic = "sr"
