functional = "pbe"
collection = "sg15"
program = "oncvpsp2"
extension = "upf"
extra = ["canonical"]
sg_suffix = "ONCV_PBE-1.2"
extracted_on = "2026-03-10T08:37:31.142"
version = "1.2"
type = "nc"
relativistic = "sr"
