functional = "pbe"
collection = "dojo"
program = "jth"
extension = "xml"
extra = ["stringent"]
pseudodojo_handle = "paw-sr-11_pbe_stringent_xml"
extracted_on = "2024-12-27T20:28:50.666"
version = "1.1"
type = "paw"
relativistic = "sr"
