functional = "pbe"
collection = "dojo"
program = "oncvpsp3"
extension = "upf"
extra = ["stringent"]
pseudodojo_handle = "nc-sr-05_pbe_stringent_upf"
extracted_on = "2024-12-27T19:59:04.730"
version = "0.5"
type = "nc"
relativistic = "sr"
