functional = "lda"
collection = "dojo"
program = "jth"
extension = "xml"
extra = ["stringent"]
pseudodojo_handle = "paw-sr-11_lda_stringent_xml"
extracted_on = "2024-12-27T20:10:20.938"
version = "1.1"
type = "paw"
relativistic = "sr"
