functional = "pbesol"
collection = "dojo"
program = "oncvpsp3"
extension = "upf"
extra = ["standard"]
pseudodojo_handle = "nc-sr-04_pbesol_standard_upf"
extracted_on = "2024-12-27T19:53:32.893"
version = "0.4.1"
type = "nc"
relativistic = "sr"
