functional = "pbesol"
collection = "dojo"
program = "jth"
extension = "xml"
extra = ["stringent"]
pseudodojo_handle = "paw-sr-11_pbesol_stringent_xml"
extracted_on = "2024-12-27T20:39:56.848"
version = "1.1"
type = "paw"
relativistic = "sr"
