functional = "pbe"
collection = "dojo"
program = "jth"
extension = "xml"
extra = ["standard"]
pseudodojo_handle = "paw-sr-11_pbe_standard_xml"
extracted_on = "2024-12-27T20:19:04.343"
version = "1.1"
type = "paw"
relativistic = "sr"
